/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/Dbv0_0_38_job_array_limits_max.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Dbv0_0_38_job_array_limits_max::Dbv0_0_38_job_array_limits_max()
{
    m_RunningIsSet = false;
}

Dbv0_0_38_job_array_limits_max::~Dbv0_0_38_job_array_limits_max()
{
}

void Dbv0_0_38_job_array_limits_max::validate()
{
    // TODO: implement validation
}

web::json::value Dbv0_0_38_job_array_limits_max::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_RunningIsSet)
    {
        val[utility::conversions::to_string_t(U("running"))] = ModelBase::toJson(m_Running);
    }

    return val;
}

bool Dbv0_0_38_job_array_limits_max::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("running"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("running")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Dbv0_0_38_job_array_limits_max_running> refVal_setRunning;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRunning);
            setRunning(refVal_setRunning);
        }
    }
    return ok;
}

void Dbv0_0_38_job_array_limits_max::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_RunningIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("running")), m_Running));
    }
}

bool Dbv0_0_38_job_array_limits_max::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("running"))))
    {
        std::shared_ptr<Dbv0_0_38_job_array_limits_max_running> refVal_setRunning;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("running"))), refVal_setRunning );
        setRunning(refVal_setRunning);
    }
    return ok;
}

std::shared_ptr<Dbv0_0_38_job_array_limits_max_running> Dbv0_0_38_job_array_limits_max::getRunning() const
{
    return m_Running;
}

void Dbv0_0_38_job_array_limits_max::setRunning(const std::shared_ptr<Dbv0_0_38_job_array_limits_max_running>& value)
{
    m_Running = value;
    m_RunningIsSet = true;
}

bool Dbv0_0_38_job_array_limits_max::runningIsSet() const
{
    return m_RunningIsSet;
}

void Dbv0_0_38_job_array_limits_max::unsetRunning()
{
    m_RunningIsSet = false;
}
}
}
}
}


