/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/Dbv0_0_38_job_step_step.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Dbv0_0_38_job_step_step::Dbv0_0_38_job_step_step()
{
    m_Job_id = 0;
    m_Job_idIsSet = false;
    m_HetIsSet = false;
    m_Id = utility::conversions::to_string_t("");
    m_IdIsSet = false;
    m_Name = utility::conversions::to_string_t("");
    m_NameIsSet = false;
}

Dbv0_0_38_job_step_step::~Dbv0_0_38_job_step_step()
{
}

void Dbv0_0_38_job_step_step::validate()
{
    // TODO: implement validation
}

web::json::value Dbv0_0_38_job_step_step::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Job_idIsSet)
    {
        val[utility::conversions::to_string_t(U("job_id"))] = ModelBase::toJson(m_Job_id);
    }
    if(m_HetIsSet)
    {
        val[utility::conversions::to_string_t(U("het"))] = ModelBase::toJson(m_Het);
    }
    if(m_IdIsSet)
    {
        val[utility::conversions::to_string_t(U("id"))] = ModelBase::toJson(m_Id);
    }
    if(m_NameIsSet)
    {
        val[utility::conversions::to_string_t(U("name"))] = ModelBase::toJson(m_Name);
    }

    return val;
}

bool Dbv0_0_38_job_step_step::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("job_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("job_id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setJobId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setJobId);
            setJobId(refVal_setJobId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("het"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("het")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Dbv0_0_38_job_step_step_het> refVal_setHet;
            ok &= ModelBase::fromJson(fieldValue, refVal_setHet);
            setHet(refVal_setHet);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("id")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setId);
            setId(refVal_setId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("name"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("name")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setName;
            ok &= ModelBase::fromJson(fieldValue, refVal_setName);
            setName(refVal_setName);
        }
    }
    return ok;
}

void Dbv0_0_38_job_step_step::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Job_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("job_id")), m_Job_id));
    }
    if(m_HetIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("het")), m_Het));
    }
    if(m_IdIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("id")), m_Id));
    }
    if(m_NameIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("name")), m_Name));
    }
}

bool Dbv0_0_38_job_step_step::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("job_id"))))
    {
        int32_t refVal_setJobId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("job_id"))), refVal_setJobId );
        setJobId(refVal_setJobId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("het"))))
    {
        std::shared_ptr<Dbv0_0_38_job_step_step_het> refVal_setHet;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("het"))), refVal_setHet );
        setHet(refVal_setHet);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("id"))))
    {
        utility::string_t refVal_setId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("id"))), refVal_setId );
        setId(refVal_setId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("name"))))
    {
        utility::string_t refVal_setName;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("name"))), refVal_setName );
        setName(refVal_setName);
    }
    return ok;
}

int32_t Dbv0_0_38_job_step_step::getJobId() const
{
    return m_Job_id;
}

void Dbv0_0_38_job_step_step::setJobId(int32_t value)
{
    m_Job_id = value;
    m_Job_idIsSet = true;
}

bool Dbv0_0_38_job_step_step::jobIdIsSet() const
{
    return m_Job_idIsSet;
}

void Dbv0_0_38_job_step_step::unsetJob_id()
{
    m_Job_idIsSet = false;
}
std::shared_ptr<Dbv0_0_38_job_step_step_het> Dbv0_0_38_job_step_step::getHet() const
{
    return m_Het;
}

void Dbv0_0_38_job_step_step::setHet(const std::shared_ptr<Dbv0_0_38_job_step_step_het>& value)
{
    m_Het = value;
    m_HetIsSet = true;
}

bool Dbv0_0_38_job_step_step::hetIsSet() const
{
    return m_HetIsSet;
}

void Dbv0_0_38_job_step_step::unsetHet()
{
    m_HetIsSet = false;
}
utility::string_t Dbv0_0_38_job_step_step::getId() const
{
    return m_Id;
}

void Dbv0_0_38_job_step_step::setId(const utility::string_t& value)
{
    m_Id = value;
    m_IdIsSet = true;
}

bool Dbv0_0_38_job_step_step::idIsSet() const
{
    return m_IdIsSet;
}

void Dbv0_0_38_job_step_step::unsetId()
{
    m_IdIsSet = false;
}
utility::string_t Dbv0_0_38_job_step_step::getName() const
{
    return m_Name;
}

void Dbv0_0_38_job_step_step::setName(const utility::string_t& value)
{
    m_Name = value;
    m_NameIsSet = true;
}

bool Dbv0_0_38_job_step_step::nameIsSet() const
{
    return m_NameIsSet;
}

void Dbv0_0_38_job_step_step::unsetName()
{
    m_NameIsSet = false;
}
}
}
}
}


