/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/Dbv0_0_39_clusters_info.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



Dbv0_0_39_clusters_info::Dbv0_0_39_clusters_info()
{
    m_MetaIsSet = false;
    m_ErrorsIsSet = false;
    m_WarningsIsSet = false;
    m_ClustersIsSet = false;
}

Dbv0_0_39_clusters_info::~Dbv0_0_39_clusters_info()
{
}

void Dbv0_0_39_clusters_info::validate()
{
    // TODO: implement validation
}

web::json::value Dbv0_0_39_clusters_info::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_MetaIsSet)
    {
        val[utility::conversions::to_string_t(U("meta"))] = ModelBase::toJson(m_Meta);
    }
    if(m_ErrorsIsSet)
    {
        val[utility::conversions::to_string_t(U("errors"))] = ModelBase::toJson(m_Errors);
    }
    if(m_WarningsIsSet)
    {
        val[utility::conversions::to_string_t(U("warnings"))] = ModelBase::toJson(m_Warnings);
    }
    if(m_ClustersIsSet)
    {
        val[utility::conversions::to_string_t(U("clusters"))] = ModelBase::toJson(m_Clusters);
    }

    return val;
}

bool Dbv0_0_39_clusters_info::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("meta"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("meta")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<Dbv0_0_39_meta> refVal_setMeta;
            ok &= ModelBase::fromJson(fieldValue, refVal_setMeta);
            setMeta(refVal_setMeta);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("errors"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("errors")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Dbv0_0_39_error>> refVal_setErrors;
            ok &= ModelBase::fromJson(fieldValue, refVal_setErrors);
            setErrors(refVal_setErrors);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("warnings"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("warnings")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<Dbv0_0_39_warning>> refVal_setWarnings;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWarnings);
            setWarnings(refVal_setWarnings);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("clusters"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("clusters")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<V0_0_39_cluster_rec>> refVal_setClusters;
            ok &= ModelBase::fromJson(fieldValue, refVal_setClusters);
            setClusters(refVal_setClusters);
        }
    }
    return ok;
}

void Dbv0_0_39_clusters_info::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_MetaIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("meta")), m_Meta));
    }
    if(m_ErrorsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("errors")), m_Errors));
    }
    if(m_WarningsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("warnings")), m_Warnings));
    }
    if(m_ClustersIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("clusters")), m_Clusters));
    }
}

bool Dbv0_0_39_clusters_info::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("meta"))))
    {
        std::shared_ptr<Dbv0_0_39_meta> refVal_setMeta;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("meta"))), refVal_setMeta );
        setMeta(refVal_setMeta);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("errors"))))
    {
        std::vector<std::shared_ptr<Dbv0_0_39_error>> refVal_setErrors;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("errors"))), refVal_setErrors );
        setErrors(refVal_setErrors);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("warnings"))))
    {
        std::vector<std::shared_ptr<Dbv0_0_39_warning>> refVal_setWarnings;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("warnings"))), refVal_setWarnings );
        setWarnings(refVal_setWarnings);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("clusters"))))
    {
        std::vector<std::shared_ptr<V0_0_39_cluster_rec>> refVal_setClusters;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("clusters"))), refVal_setClusters );
        setClusters(refVal_setClusters);
    }
    return ok;
}

std::shared_ptr<Dbv0_0_39_meta> Dbv0_0_39_clusters_info::getMeta() const
{
    return m_Meta;
}

void Dbv0_0_39_clusters_info::setMeta(const std::shared_ptr<Dbv0_0_39_meta>& value)
{
    m_Meta = value;
    m_MetaIsSet = true;
}

bool Dbv0_0_39_clusters_info::metaIsSet() const
{
    return m_MetaIsSet;
}

void Dbv0_0_39_clusters_info::unsetMeta()
{
    m_MetaIsSet = false;
}
std::vector<std::shared_ptr<Dbv0_0_39_error>>& Dbv0_0_39_clusters_info::getErrors()
{
    return m_Errors;
}

void Dbv0_0_39_clusters_info::setErrors(const std::vector<std::shared_ptr<Dbv0_0_39_error>>& value)
{
    m_Errors = value;
    m_ErrorsIsSet = true;
}

bool Dbv0_0_39_clusters_info::errorsIsSet() const
{
    return m_ErrorsIsSet;
}

void Dbv0_0_39_clusters_info::unsetErrors()
{
    m_ErrorsIsSet = false;
}
std::vector<std::shared_ptr<Dbv0_0_39_warning>>& Dbv0_0_39_clusters_info::getWarnings()
{
    return m_Warnings;
}

void Dbv0_0_39_clusters_info::setWarnings(const std::vector<std::shared_ptr<Dbv0_0_39_warning>>& value)
{
    m_Warnings = value;
    m_WarningsIsSet = true;
}

bool Dbv0_0_39_clusters_info::warningsIsSet() const
{
    return m_WarningsIsSet;
}

void Dbv0_0_39_clusters_info::unsetWarnings()
{
    m_WarningsIsSet = false;
}
std::vector<std::shared_ptr<V0_0_39_cluster_rec>>& Dbv0_0_39_clusters_info::getClusters()
{
    return m_Clusters;
}

void Dbv0_0_39_clusters_info::setClusters(const std::vector<std::shared_ptr<V0_0_39_cluster_rec>>& value)
{
    m_Clusters = value;
    m_ClustersIsSet = true;
}

bool Dbv0_0_39_clusters_info::clustersIsSet() const
{
    return m_ClustersIsSet;
}

void Dbv0_0_39_clusters_info::unsetClusters()
{
    m_ClustersIsSet = false;
}
}
}
}
}


