/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_39_job_submission.h"

namespace hm {
namespace slurm {
namespace client {
namespace model {



V0_0_39_job_submission::V0_0_39_job_submission()
{
    m_Script = utility::conversions::to_string_t("");
    m_ScriptIsSet = false;
    m_JobIsSet = false;
    m_JobsIsSet = false;
}

V0_0_39_job_submission::~V0_0_39_job_submission()
{
}

void V0_0_39_job_submission::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_39_job_submission::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ScriptIsSet)
    {
        val[utility::conversions::to_string_t(U("script"))] = ModelBase::toJson(m_Script);
    }
    if(m_JobIsSet)
    {
        val[utility::conversions::to_string_t(U("job"))] = ModelBase::toJson(m_Job);
    }
    if(m_JobsIsSet)
    {
        val[utility::conversions::to_string_t(U("jobs"))] = ModelBase::toJson(m_Jobs);
    }

    return val;
}

bool V0_0_39_job_submission::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("script"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("script")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setScript;
            ok &= ModelBase::fromJson(fieldValue, refVal_setScript);
            setScript(refVal_setScript);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("job"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("job")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<V0_0_39_job_desc_msg> refVal_setJob;
            ok &= ModelBase::fromJson(fieldValue, refVal_setJob);
            setJob(refVal_setJob);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("jobs"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("jobs")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<V0_0_39_job_desc_msg>> refVal_setJobs;
            ok &= ModelBase::fromJson(fieldValue, refVal_setJobs);
            setJobs(refVal_setJobs);
        }
    }
    return ok;
}

void V0_0_39_job_submission::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ScriptIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("script")), m_Script));
    }
    if(m_JobIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("job")), m_Job));
    }
    if(m_JobsIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("jobs")), m_Jobs));
    }
}

bool V0_0_39_job_submission::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("script"))))
    {
        utility::string_t refVal_setScript;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("script"))), refVal_setScript );
        setScript(refVal_setScript);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("job"))))
    {
        std::shared_ptr<V0_0_39_job_desc_msg> refVal_setJob;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("job"))), refVal_setJob );
        setJob(refVal_setJob);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("jobs"))))
    {
        std::vector<std::shared_ptr<V0_0_39_job_desc_msg>> refVal_setJobs;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("jobs"))), refVal_setJobs );
        setJobs(refVal_setJobs);
    }
    return ok;
}

utility::string_t V0_0_39_job_submission::getScript() const
{
    return m_Script;
}

void V0_0_39_job_submission::setScript(const utility::string_t& value)
{
    m_Script = value;
    m_ScriptIsSet = true;
}

bool V0_0_39_job_submission::scriptIsSet() const
{
    return m_ScriptIsSet;
}

void V0_0_39_job_submission::unsetScript()
{
    m_ScriptIsSet = false;
}
std::shared_ptr<V0_0_39_job_desc_msg> V0_0_39_job_submission::getJob() const
{
    return m_Job;
}

void V0_0_39_job_submission::setJob(const std::shared_ptr<V0_0_39_job_desc_msg>& value)
{
    m_Job = value;
    m_JobIsSet = true;
}

bool V0_0_39_job_submission::jobIsSet() const
{
    return m_JobIsSet;
}

void V0_0_39_job_submission::unsetJob()
{
    m_JobIsSet = false;
}
std::vector<std::shared_ptr<V0_0_39_job_desc_msg>>& V0_0_39_job_submission::getJobs()
{
    return m_Jobs;
}

void V0_0_39_job_submission::setJobs(const std::vector<std::shared_ptr<V0_0_39_job_desc_msg>>& value)
{
    m_Jobs = value;
    m_JobsIsSet = true;
}

bool V0_0_39_job_submission::jobsIsSet() const
{
    return m_JobsIsSet;
}

void V0_0_39_job_submission::unsetJobs()
{
    m_JobsIsSet = false;
}
}
}
}
}


