/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_38_diag_rpcu.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_38_diag_rpcu::V0_0_38_diag_rpcu()
{
    m_User = utility::conversions::to_string_t("");
    m_UserIsSet = false;
    m_User_id = 0;
    m_User_idIsSet = false;
    m_Count = 0;
    m_CountIsSet = false;
    m_Average_time = 0;
    m_Average_timeIsSet = false;
    m_Total_time = 0;
    m_Total_timeIsSet = false;
}

V0_0_38_diag_rpcu::~V0_0_38_diag_rpcu()
{
}

void V0_0_38_diag_rpcu::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_38_diag_rpcu::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_UserIsSet)
    {
        val[utility::conversions::to_string_t(U("user"))] = ModelBase::toJson(m_User);
    }
    if(m_User_idIsSet)
    {
        val[utility::conversions::to_string_t(U("user_id"))] = ModelBase::toJson(m_User_id);
    }
    if(m_CountIsSet)
    {
        val[utility::conversions::to_string_t(U("count"))] = ModelBase::toJson(m_Count);
    }
    if(m_Average_timeIsSet)
    {
        val[utility::conversions::to_string_t(U("average_time"))] = ModelBase::toJson(m_Average_time);
    }
    if(m_Total_timeIsSet)
    {
        val[utility::conversions::to_string_t(U("total_time"))] = ModelBase::toJson(m_Total_time);
    }

    return val;
}

bool V0_0_38_diag_rpcu::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("user"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("user")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setUser;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUser);
            setUser(refVal_setUser);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("user_id"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("user_id")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setUserId;
            ok &= ModelBase::fromJson(fieldValue, refVal_setUserId);
            setUserId(refVal_setUserId);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("count"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("count")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setCount;
            ok &= ModelBase::fromJson(fieldValue, refVal_setCount);
            setCount(refVal_setCount);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("average_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("average_time")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setAverageTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAverageTime);
            setAverageTime(refVal_setAverageTime);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total_time"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total_time")));
        if(!fieldValue.is_null())
        {
            int32_t refVal_setTotalTime;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotalTime);
            setTotalTime(refVal_setTotalTime);
        }
    }
    return ok;
}

void V0_0_38_diag_rpcu::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_UserIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("user")), m_User));
    }
    if(m_User_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("user_id")), m_User_id));
    }
    if(m_CountIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("count")), m_Count));
    }
    if(m_Average_timeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("average_time")), m_Average_time));
    }
    if(m_Total_timeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total_time")), m_Total_time));
    }
}

bool V0_0_38_diag_rpcu::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("user"))))
    {
        utility::string_t refVal_setUser;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("user"))), refVal_setUser );
        setUser(refVal_setUser);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("user_id"))))
    {
        int32_t refVal_setUserId;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("user_id"))), refVal_setUserId );
        setUserId(refVal_setUserId);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("count"))))
    {
        int32_t refVal_setCount;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("count"))), refVal_setCount );
        setCount(refVal_setCount);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("average_time"))))
    {
        int32_t refVal_setAverageTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("average_time"))), refVal_setAverageTime );
        setAverageTime(refVal_setAverageTime);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total_time"))))
    {
        int32_t refVal_setTotalTime;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total_time"))), refVal_setTotalTime );
        setTotalTime(refVal_setTotalTime);
    }
    return ok;
}

utility::string_t V0_0_38_diag_rpcu::getUser() const
{
    return m_User;
}

void V0_0_38_diag_rpcu::setUser(const utility::string_t& value)
{
    m_User = value;
    m_UserIsSet = true;
}

bool V0_0_38_diag_rpcu::userIsSet() const
{
    return m_UserIsSet;
}

void V0_0_38_diag_rpcu::unsetUser()
{
    m_UserIsSet = false;
}
int32_t V0_0_38_diag_rpcu::getUserId() const
{
    return m_User_id;
}

void V0_0_38_diag_rpcu::setUserId(int32_t value)
{
    m_User_id = value;
    m_User_idIsSet = true;
}

bool V0_0_38_diag_rpcu::userIdIsSet() const
{
    return m_User_idIsSet;
}

void V0_0_38_diag_rpcu::unsetUser_id()
{
    m_User_idIsSet = false;
}
int32_t V0_0_38_diag_rpcu::getCount() const
{
    return m_Count;
}

void V0_0_38_diag_rpcu::setCount(int32_t value)
{
    m_Count = value;
    m_CountIsSet = true;
}

bool V0_0_38_diag_rpcu::countIsSet() const
{
    return m_CountIsSet;
}

void V0_0_38_diag_rpcu::unsetCount()
{
    m_CountIsSet = false;
}
int32_t V0_0_38_diag_rpcu::getAverageTime() const
{
    return m_Average_time;
}

void V0_0_38_diag_rpcu::setAverageTime(int32_t value)
{
    m_Average_time = value;
    m_Average_timeIsSet = true;
}

bool V0_0_38_diag_rpcu::averageTimeIsSet() const
{
    return m_Average_timeIsSet;
}

void V0_0_38_diag_rpcu::unsetAverage_time()
{
    m_Average_timeIsSet = false;
}
int32_t V0_0_38_diag_rpcu::getTotalTime() const
{
    return m_Total_time;
}

void V0_0_38_diag_rpcu::setTotalTime(int32_t value)
{
    m_Total_time = value;
    m_Total_timeIsSet = true;
}

bool V0_0_38_diag_rpcu::totalTimeIsSet() const
{
    return m_Total_timeIsSet;
}

void V0_0_38_diag_rpcu::unsetTotal_time()
{
    m_Total_timeIsSet = false;
}
}
}
}
}


