/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_40_qos_limits_min_tres.h"

namespace hm {
namespace slurm {
namespace client {
namespace model {



V0_0_40_qos_limits_min_tres::V0_0_40_qos_limits_min_tres()
{
    m_PerIsSet = false;
}

V0_0_40_qos_limits_min_tres::~V0_0_40_qos_limits_min_tres()
{
}

void V0_0_40_qos_limits_min_tres::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_40_qos_limits_min_tres::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_PerIsSet)
    {
        val[utility::conversions::to_string_t(U("per"))] = ModelBase::toJson(m_Per);
    }

    return val;
}

bool V0_0_40_qos_limits_min_tres::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("per"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("per")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<V0_0_40_qos_limits_min_tres_per> refVal_setPer;
            ok &= ModelBase::fromJson(fieldValue, refVal_setPer);
            setPer(refVal_setPer);
        }
    }
    return ok;
}

void V0_0_40_qos_limits_min_tres::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_PerIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("per")), m_Per));
    }
}

bool V0_0_40_qos_limits_min_tres::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("per"))))
    {
        std::shared_ptr<V0_0_40_qos_limits_min_tres_per> refVal_setPer;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("per"))), refVal_setPer );
        setPer(refVal_setPer);
    }
    return ok;
}

std::shared_ptr<V0_0_40_qos_limits_min_tres_per> V0_0_40_qos_limits_min_tres::getPer() const
{
    return m_Per;
}

void V0_0_40_qos_limits_min_tres::setPer(const std::shared_ptr<V0_0_40_qos_limits_min_tres_per>& value)
{
    m_Per = value;
    m_PerIsSet = true;
}

bool V0_0_40_qos_limits_min_tres::perIsSet() const
{
    return m_PerIsSet;
}

void V0_0_40_qos_limits_min_tres::unsetPer()
{
    m_PerIsSet = false;
}
}
}
}
}


