/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_39_job_tres.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_39_job_tres::V0_0_39_job_tres()
{
    m_RequestedIsSet = false;
}

V0_0_39_job_tres::~V0_0_39_job_tres()
{
}

void V0_0_39_job_tres::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_39_job_tres::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_RequestedIsSet)
    {
        val[utility::conversions::to_string_t(U("requested"))] = ModelBase::toJson(m_Requested);
    }

    return val;
}

bool V0_0_39_job_tres::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("requested"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("requested")));
        if(!fieldValue.is_null())
        {
            std::vector<std::shared_ptr<V0_0_39_tres>> refVal_setRequested;
            ok &= ModelBase::fromJson(fieldValue, refVal_setRequested);
            setRequested(refVal_setRequested);
        }
    }
    return ok;
}

void V0_0_39_job_tres::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_RequestedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("requested")), m_Requested));
    }
}

bool V0_0_39_job_tres::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("requested"))))
    {
        std::vector<std::shared_ptr<V0_0_39_tres>> refVal_setRequested;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("requested"))), refVal_setRequested );
        setRequested(refVal_setRequested);
    }
    return ok;
}

std::vector<std::shared_ptr<V0_0_39_tres>>& V0_0_39_job_tres::getRequested()
{
    return m_Requested;
}

void V0_0_39_job_tres::setRequested(const std::vector<std::shared_ptr<V0_0_39_tres>>& value)
{
    m_Requested = value;
    m_RequestedIsSet = true;
}

bool V0_0_39_job_tres::requestedIsSet() const
{
    return m_RequestedIsSet;
}

void V0_0_39_job_tres::unsetRequested()
{
    m_RequestedIsSet = false;
}
}
}
}
}


