/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_39_job_array.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_39_job_array::V0_0_39_job_array()
{
    m_Task = utility::conversions::to_string_t("");
    m_TaskIsSet = false;
}

V0_0_39_job_array::~V0_0_39_job_array()
{
}

void V0_0_39_job_array::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_39_job_array::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_TaskIsSet)
    {
        val[utility::conversions::to_string_t(U("task"))] = ModelBase::toJson(m_Task);
    }

    return val;
}

bool V0_0_39_job_array::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("task"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("task")));
        if(!fieldValue.is_null())
        {
            utility::string_t refVal_setTask;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTask);
            setTask(refVal_setTask);
        }
    }
    return ok;
}

void V0_0_39_job_array::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_TaskIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("task")), m_Task));
    }
}

bool V0_0_39_job_array::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("task"))))
    {
        utility::string_t refVal_setTask;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("task"))), refVal_setTask );
        setTask(refVal_setTask);
    }
    return ok;
}

utility::string_t V0_0_39_job_array::getTask() const
{
    return m_Task;
}

void V0_0_39_job_array::setTask(const utility::string_t& value)
{
    m_Task = value;
    m_TaskIsSet = true;
}

bool V0_0_39_job_array::taskIsSet() const
{
    return m_TaskIsSet;
}

void V0_0_39_job_array::unsetTask()
{
    m_TaskIsSet = false;
}
}
}
}
}


