/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account.h"

namespace hm {
namespace slurm {
namespace client {
namespace model {



V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account()
{
    m_Wall_clockIsSet = false;
}

V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::~V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account()
{
}

void V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Wall_clockIsSet)
    {
        val[utility::conversions::to_string_t(U("wall_clock"))] = ModelBase::toJson(m_Wall_clock);
    }

    return val;
}

bool V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("wall_clock"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("wall_clock")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<V0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_qos> refVal_setWallClock;
            ok &= ModelBase::fromJson(fieldValue, refVal_setWallClock);
            setWallClock(refVal_setWallClock);
        }
    }
    return ok;
}

void V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Wall_clockIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("wall_clock")), m_Wall_clock));
    }
}

bool V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("wall_clock"))))
    {
        std::shared_ptr<V0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_qos> refVal_setWallClock;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("wall_clock"))), refVal_setWallClock );
        setWallClock(refVal_setWallClock);
    }
    return ok;
}

std::shared_ptr<V0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_qos> V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::getWallClock() const
{
    return m_Wall_clock;
}

void V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::setWallClock(const std::shared_ptr<V0_0_41_openapi_slurmdbd_config_resp_qos_inner_limits_max_wall_clock_per_qos>& value)
{
    m_Wall_clock = value;
    m_Wall_clockIsSet = true;
}

bool V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::wallClockIsSet() const
{
    return m_Wall_clockIsSet;
}

void V0_0_41_openapi_slurmdbd_config_resp_associations_inner_max_per_account::unsetWall_clock()
{
    m_Wall_clockIsSet = false;
}
}
}
}
}


