/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_40_stats_rpc_time.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_40_stats_rpc_time::V0_0_40_stats_rpc_time()
{
    m_Average = 0L;
    m_AverageIsSet = false;
    m_Total = 0L;
    m_TotalIsSet = false;
}

V0_0_40_stats_rpc_time::~V0_0_40_stats_rpc_time()
{
}

void V0_0_40_stats_rpc_time::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_40_stats_rpc_time::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_AverageIsSet)
    {
        val[utility::conversions::to_string_t(U("average"))] = ModelBase::toJson(m_Average);
    }
    if(m_TotalIsSet)
    {
        val[utility::conversions::to_string_t(U("total"))] = ModelBase::toJson(m_Total);
    }

    return val;
}

bool V0_0_40_stats_rpc_time::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("average"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("average")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setAverage;
            ok &= ModelBase::fromJson(fieldValue, refVal_setAverage);
            setAverage(refVal_setAverage);
        }
    }
    if(val.has_field(utility::conversions::to_string_t(U("total"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("total")));
        if(!fieldValue.is_null())
        {
            int64_t refVal_setTotal;
            ok &= ModelBase::fromJson(fieldValue, refVal_setTotal);
            setTotal(refVal_setTotal);
        }
    }
    return ok;
}

void V0_0_40_stats_rpc_time::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_AverageIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("average")), m_Average));
    }
    if(m_TotalIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("total")), m_Total));
    }
}

bool V0_0_40_stats_rpc_time::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("average"))))
    {
        int64_t refVal_setAverage;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("average"))), refVal_setAverage );
        setAverage(refVal_setAverage);
    }
    if(multipart->hasContent(utility::conversions::to_string_t(U("total"))))
    {
        int64_t refVal_setTotal;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("total"))), refVal_setTotal );
        setTotal(refVal_setTotal);
    }
    return ok;
}

int64_t V0_0_40_stats_rpc_time::getAverage() const
{
    return m_Average;
}

void V0_0_40_stats_rpc_time::setAverage(int64_t value)
{
    m_Average = value;
    m_AverageIsSet = true;
}

bool V0_0_40_stats_rpc_time::averageIsSet() const
{
    return m_AverageIsSet;
}

void V0_0_40_stats_rpc_time::unsetAverage()
{
    m_AverageIsSet = false;
}
int64_t V0_0_40_stats_rpc_time::getTotal() const
{
    return m_Total;
}

void V0_0_40_stats_rpc_time::setTotal(int64_t value)
{
    m_Total = value;
    m_TotalIsSet = true;
}

bool V0_0_40_stats_rpc_time::totalIsSet() const
{
    return m_TotalIsSet;
}

void V0_0_40_stats_rpc_time::unsetTotal()
{
    m_TotalIsSet = false;
}
}
}
}
}


