/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_39_step_statistics_energy.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_39_step_statistics_energy::V0_0_39_step_statistics_energy()
{
    m_ConsumedIsSet = false;
}

V0_0_39_step_statistics_energy::~V0_0_39_step_statistics_energy()
{
}

void V0_0_39_step_statistics_energy::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_39_step_statistics_energy::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_ConsumedIsSet)
    {
        val[utility::conversions::to_string_t(U("consumed"))] = ModelBase::toJson(m_Consumed);
    }

    return val;
}

bool V0_0_39_step_statistics_energy::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("consumed"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("consumed")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<V0_0_39_uint64_no_val> refVal_setConsumed;
            ok &= ModelBase::fromJson(fieldValue, refVal_setConsumed);
            setConsumed(refVal_setConsumed);
        }
    }
    return ok;
}

void V0_0_39_step_statistics_energy::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_ConsumedIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("consumed")), m_Consumed));
    }
}

bool V0_0_39_step_statistics_energy::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("consumed"))))
    {
        std::shared_ptr<V0_0_39_uint64_no_val> refVal_setConsumed;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("consumed"))), refVal_setConsumed );
        setConsumed(refVal_setConsumed);
    }
    return ok;
}

std::shared_ptr<V0_0_39_uint64_no_val> V0_0_39_step_statistics_energy::getConsumed() const
{
    return m_Consumed;
}

void V0_0_39_step_statistics_energy::setConsumed(const std::shared_ptr<V0_0_39_uint64_no_val>& value)
{
    m_Consumed = value;
    m_ConsumedIsSet = true;
}

bool V0_0_39_step_statistics_energy::consumedIsSet() const
{
    return m_ConsumedIsSet;
}

void V0_0_39_step_statistics_energy::unsetConsumed()
{
    m_ConsumedIsSet = false;
}
}
}
}
}


