/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



#include "slurmrestapi/model/V0_0_39_partition_info_maximums.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {



V0_0_39_partition_info_maximums::V0_0_39_partition_info_maximums()
{
    m_Over_time_limitIsSet = false;
}

V0_0_39_partition_info_maximums::~V0_0_39_partition_info_maximums()
{
}

void V0_0_39_partition_info_maximums::validate()
{
    // TODO: implement validation
}

web::json::value V0_0_39_partition_info_maximums::toJson() const
{

    web::json::value val = web::json::value::object();
    
    if(m_Over_time_limitIsSet)
    {
        val[utility::conversions::to_string_t(U("over_time_limit"))] = ModelBase::toJson(m_Over_time_limit);
    }

    return val;
}

bool V0_0_39_partition_info_maximums::fromJson(const web::json::value& val)
{
    bool ok = true;
    
    if(val.has_field(utility::conversions::to_string_t(U("over_time_limit"))))
    {
        const web::json::value& fieldValue = val.at(utility::conversions::to_string_t(U("over_time_limit")));
        if(!fieldValue.is_null())
        {
            std::shared_ptr<V0_0_39_uint16_no_val> refVal_setOverTimeLimit;
            ok &= ModelBase::fromJson(fieldValue, refVal_setOverTimeLimit);
            setOverTimeLimit(refVal_setOverTimeLimit);
        }
    }
    return ok;
}

void V0_0_39_partition_info_maximums::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }
    if(m_Over_time_limitIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + utility::conversions::to_string_t(U("over_time_limit")), m_Over_time_limit));
    }
}

bool V0_0_39_partition_info_maximums::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    bool ok = true;
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix.substr(namePrefix.size() - 1) != utility::conversions::to_string_t(U(".")))
    {
        namePrefix += utility::conversions::to_string_t(U("."));
    }

    if(multipart->hasContent(utility::conversions::to_string_t(U("over_time_limit"))))
    {
        std::shared_ptr<V0_0_39_uint16_no_val> refVal_setOverTimeLimit;
        ok &= ModelBase::fromHttpContent(multipart->getContent(utility::conversions::to_string_t(U("over_time_limit"))), refVal_setOverTimeLimit );
        setOverTimeLimit(refVal_setOverTimeLimit);
    }
    return ok;
}

std::shared_ptr<V0_0_39_uint16_no_val> V0_0_39_partition_info_maximums::getOverTimeLimit() const
{
    return m_Over_time_limit;
}

void V0_0_39_partition_info_maximums::setOverTimeLimit(const std::shared_ptr<V0_0_39_uint16_no_val>& value)
{
    m_Over_time_limit = value;
    m_Over_time_limitIsSet = true;
}

bool V0_0_39_partition_info_maximums::overTimeLimitIsSet() const
{
    return m_Over_time_limitIsSet;
}

void V0_0_39_partition_info_maximums::unsetOver_time_limit()
{
    m_Over_time_limitIsSet = false;
}
}
}
}
}


