/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Dbv0_0_37_qos_limits_min.h
 *
 * Min limit settings
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_qos_limits_min_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_qos_limits_min_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/Dbv0_0_37_qos_limits_min_tres.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Dbv0_0_37_qos_limits_min_tres;

/// <summary>
/// Min limit settings
/// </summary>
class  Dbv0_0_37_qos_limits_min
    : public ModelBase
{
public:
    Dbv0_0_37_qos_limits_min();
    virtual ~Dbv0_0_37_qos_limits_min();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Dbv0_0_37_qos_limits_min members

    /// <summary>
    /// Min priority threshold
    /// </summary>
    int32_t getPriorityThreshold() const;
    bool priorityThresholdIsSet() const;
    void unsetPriority_threshold();

    void setPriorityThreshold(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Dbv0_0_37_qos_limits_min_tres> getTres() const;
    bool tresIsSet() const;
    void unsetTres();

    void setTres(const std::shared_ptr<Dbv0_0_37_qos_limits_min_tres>& value);


protected:
    int32_t m_Priority_threshold;
    bool m_Priority_thresholdIsSet;
    std::shared_ptr<Dbv0_0_37_qos_limits_min_tres> m_Tres;
    bool m_TresIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_qos_limits_min_H_ */
