/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Dbv0_0_38_qos_limits.h
 *
 * Assigned limits
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_qos_limits_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_qos_limits_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/Dbv0_0_38_qos_limits_max.h"
#include "slurmrestapi/model/Dbv0_0_38_qos_limits_min.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Dbv0_0_38_qos_limits_max;
class Dbv0_0_38_qos_limits_min;

/// <summary>
/// Assigned limits
/// </summary>
class  Dbv0_0_38_qos_limits
    : public ModelBase
{
public:
    Dbv0_0_38_qos_limits();
    virtual ~Dbv0_0_38_qos_limits();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Dbv0_0_38_qos_limits members

    /// <summary>
    /// factor to apply to TRES count for associations using this QOS
    /// </summary>
    double getFactor() const;
    bool factorIsSet() const;
    void unsetFactor();

    void setFactor(double value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Dbv0_0_38_qos_limits_max> getMax() const;
    bool maxIsSet() const;
    void unsetMax();

    void setMax(const std::shared_ptr<Dbv0_0_38_qos_limits_max>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Dbv0_0_38_qos_limits_min> getMin() const;
    bool minIsSet() const;
    void unsetMin();

    void setMin(const std::shared_ptr<Dbv0_0_38_qos_limits_min>& value);


protected:
    double m_Factor;
    bool m_FactorIsSet;
    std::shared_ptr<Dbv0_0_38_qos_limits_max> m_Max;
    bool m_MaxIsSet;
    std::shared_ptr<Dbv0_0_38_qos_limits_min> m_Min;
    bool m_MinIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_qos_limits_H_ */
