/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Dbv0_0_37_job_step_step.h
 *
 * Step details
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_job_step_step_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_job_step_step_H_


#include "slurmrestapi/ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "slurmrestapi/model/Dbv0_0_37_job_step_step_het.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Dbv0_0_37_job_step_step_het;

/// <summary>
/// Step details
/// </summary>
class  Dbv0_0_37_job_step_step
    : public ModelBase
{
public:
    Dbv0_0_37_job_step_step();
    virtual ~Dbv0_0_37_job_step_step();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Dbv0_0_37_job_step_step members

    /// <summary>
    /// Parent job id
    /// </summary>
    int32_t getJobId() const;
    bool jobIdIsSet() const;
    void unsetJob_id();

    void setJobId(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Dbv0_0_37_job_step_step_het> getHet() const;
    bool hetIsSet() const;
    void unsetHet();

    void setHet(const std::shared_ptr<Dbv0_0_37_job_step_step_het>& value);

    /// <summary>
    /// Step id
    /// </summary>
    utility::string_t getId() const;
    bool idIsSet() const;
    void unsetId();

    void setId(const utility::string_t& value);

    /// <summary>
    /// Step name
    /// </summary>
    utility::string_t getName() const;
    bool nameIsSet() const;
    void unsetName();

    void setName(const utility::string_t& value);


protected:
    int32_t m_Job_id;
    bool m_Job_idIsSet;
    std::shared_ptr<Dbv0_0_37_job_step_step_het> m_Het;
    bool m_HetIsSet;
    utility::string_t m_Id;
    bool m_IdIsSet;
    utility::string_t m_Name;
    bool m_NameIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_37_job_step_step_H_ */
