/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * Dbv0_0_38_update_users.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_update_users_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_update_users_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/Dbv0_0_38_user.h"
#include <vector>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class Dbv0_0_38_user;

/// <summary>
/// 
/// </summary>
class  Dbv0_0_38_update_users
    : public ModelBase
{
public:
    Dbv0_0_38_update_users();
    virtual ~Dbv0_0_38_update_users();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Dbv0_0_38_update_users members

    /// <summary>
    /// 
    /// </summary>
    std::vector<std::shared_ptr<Dbv0_0_38_user>>& getUsers();
    bool usersIsSet() const;
    void unsetUsers();

    void setUsers(const std::vector<std::shared_ptr<Dbv0_0_38_user>>& value);


protected:
    std::vector<std::shared_ptr<Dbv0_0_38_user>> m_Users;
    bool m_UsersIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_Dbv0_0_38_update_users_H_ */
