/**
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.38
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.6.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V0_0_38_node_allocation.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_38_node_allocation_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_38_node_allocation_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/V0_0_38_node_allocation_sockets.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class V0_0_38_node_allocation_sockets;

/// <summary>
/// 
/// </summary>
class  V0_0_38_node_allocation
    : public ModelBase
{
public:
    V0_0_38_node_allocation();
    virtual ~V0_0_38_node_allocation();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// V0_0_38_node_allocation members

    /// <summary>
    /// amount of assigned job memory
    /// </summary>
    int32_t getMemory() const;
    bool memoryIsSet() const;
    void unsetMemory();

    void setMemory(int32_t value);

    /// <summary>
    /// number of assigned job CPUs
    /// </summary>
    int32_t getCpus() const;
    bool cpusIsSet() const;
    void unsetCpus();

    void setCpus(int32_t value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<V0_0_38_node_allocation_sockets> getSockets() const;
    bool socketsIsSet() const;
    void unsetSockets();

    void setSockets(const std::shared_ptr<V0_0_38_node_allocation_sockets>& value);

    /// <summary>
    /// node name
    /// </summary>
    utility::string_t getNodename() const;
    bool nodenameIsSet() const;
    void unsetNodename();

    void setNodename(const utility::string_t& value);


protected:
    int32_t m_Memory;
    bool m_MemoryIsSet;
    int32_t m_Cpus;
    bool m_CpusIsSet;
    std::shared_ptr<V0_0_38_node_allocation_sockets> m_Sockets;
    bool m_SocketsIsSet;
    utility::string_t m_Nodename;
    bool m_NodenameIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_38_node_allocation_H_ */
