/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V0_0_39_qos_limits.h
 *
 * 
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_39_qos_limits_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_39_qos_limits_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/V0_0_39_uint32_no_val.h"
#include "slurmrestapi/model/V0_0_39_qos_limits_max.h"
#include "slurmrestapi/model/V0_0_39_qos_limits_min.h"

namespace org {
namespace openapitools {
namespace client {
namespace model {

class V0_0_39_uint32_no_val;
class V0_0_39_qos_limits_max;
class V0_0_39_qos_limits_min;


/// <summary>
/// 
/// </summary>
class  V0_0_39_qos_limits
    : public ModelBase
{
public:
    V0_0_39_qos_limits();
    virtual ~V0_0_39_qos_limits();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// V0_0_39_qos_limits members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<V0_0_39_uint32_no_val> getGraceTime() const;
    bool graceTimeIsSet() const;
    void unsetGrace_time();

    void setGraceTime(const std::shared_ptr<V0_0_39_uint32_no_val>& value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<V0_0_39_qos_limits_max> getMax() const;
    bool maxIsSet() const;
    void unsetMax();

    void setMax(const std::shared_ptr<V0_0_39_qos_limits_max>& value);

    /// <summary>
    /// 
    /// </summary>
    double getFactor() const;
    bool factorIsSet() const;
    void unsetFactor();

    void setFactor(double value);

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<V0_0_39_qos_limits_min> getMin() const;
    bool minIsSet() const;
    void unsetMin();

    void setMin(const std::shared_ptr<V0_0_39_qos_limits_min>& value);


protected:
    std::shared_ptr<V0_0_39_uint32_no_val> m_Grace_time;
    bool m_Grace_timeIsSet;
    std::shared_ptr<V0_0_39_qos_limits_max> m_Max;
    bool m_MaxIsSet;
    double m_Factor;
    bool m_FactorIsSet;
    std::shared_ptr<V0_0_39_qos_limits_min> m_Min;
    bool m_MinIsSet;
};


}
}
}
}

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_V0_0_39_qos_limits_H_ */
