/**
 * Slurm REST API
 * API to access and control Slurm
 *
 * The version of the OpenAPI document: Slurm-24.05.5&openapi/dbv0.0.39&openapi/slurmctld&openapi/slurmdbd&openapi/v0.0.39
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 7.10.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * V0_0_41_openapi_shares_resp_shares_shares_inner_tres.h
 *
 * 
 */

#ifndef HM_SLURM_CLIENT_MODEL_V0_0_41_openapi_shares_resp_shares_shares_inner_tres_H_
#define HM_SLURM_CLIENT_MODEL_V0_0_41_openapi_shares_resp_shares_shares_inner_tres_H_


#include "slurmrestapi/ModelBase.h"

#include "slurmrestapi/model/V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner.h"
#include "slurmrestapi/model/V0_0_41_openapi_shares_resp_shares_shares_inner_tres_usage_inner.h"
#include <vector>

namespace hm {
namespace slurm {
namespace client {
namespace model {

class V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner;
class V0_0_41_openapi_shares_resp_shares_shares_inner_tres_usage_inner;


/// <summary>
/// 
/// </summary>
class  V0_0_41_openapi_shares_resp_shares_shares_inner_tres
    : public ModelBase
{
public:
    V0_0_41_openapi_shares_resp_shares_shares_inner_tres();
    virtual ~V0_0_41_openapi_shares_resp_shares_shares_inner_tres();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    bool fromJson(const web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// V0_0_41_openapi_shares_resp_shares_shares_inner_tres members

    /// <summary>
    /// Currently running tres-secs &#x3D; grp_used_tres_run_secs
    /// </summary>
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>>& getRunSeconds();
    bool runSecondsIsSet() const;
    void unsetRun_seconds();

    void setRunSeconds(const std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>>& value);

    /// <summary>
    /// TRES-minute limit
    /// </summary>
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>>& getGroupMinutes();
    bool groupMinutesIsSet() const;
    void unsetGroup_minutes();

    void setGroupMinutes(const std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>>& value);

    /// <summary>
    /// Measure of each TRES usage
    /// </summary>
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_usage_inner>>& getUsage();
    bool usageIsSet() const;
    void unsetUsage();

    void setUsage(const std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_usage_inner>>& value);


protected:
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>> m_Run_seconds;
    bool m_Run_secondsIsSet;
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_run_seconds_inner>> m_Group_minutes;
    bool m_Group_minutesIsSet;
    std::vector<std::shared_ptr<V0_0_41_openapi_shares_resp_shares_shares_inner_tres_usage_inner>> m_Usage;
    bool m_UsageIsSet;
};


}
}
}
}

#endif /* HM_SLURM_CLIENT_MODEL_V0_0_41_openapi_shares_resp_shares_shares_inner_tres_H_ */
